#### 花哨的索引

In [1]:
# 花哨的索引传递一个索引（下标）数组，来一次性获得多个数组元素
import numpy as np
np.random.seed(1)
a = np.random.randint(1, 100, 20)
a

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2, 77, 72,  7, 26, 51, 21, 19,
       85, 12, 29])

In [2]:
# 若想获得索引0,5,10,15的元素，可以通过下面方式得到
[a[0], a[5], a[10], a[15]]

[38, 6, 77, 21]

In [3]:
# 但更好的方法是用花哨的索引
ind1 = [0, 5, 10, 15]
a[ind1]

array([38,  6, 77, 21])

In [4]:
# 一个重要的特点，利用花哨索引，结果的形状跟索引一致，这在一些场景下，非常游泳
ind2 = np.array([[0, 5], [10, 15]])
a[ind2]

array([[38,  6],
       [77, 21]])

In [5]:
# 花哨的索引也可以用于多维数组，这是第一个索引指的是行，第二个索引指的是列
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
row = np.array([0, 1, 2]) # 行索引（下标）
col = np.array([2, 1, 3]) # 列索引（下标）
a[row, col] # 得到的是a[0, 2], a[1, 1], a[2, 3]构成的数组

array([ 2,  5, 11])

In [7]:
# 花哨索引的配对规则满足前面介绍过的广播规则
ind = row[:, np.newaxis], col
ind

(array([[0],
        [1],
        [2]]),
 array([2, 1, 3]))

In [8]:
a[ind] # ind是形状为(3, 1)和(3,)配对，经过右对齐广播之后，形成一个(3, 3)的索引数组，因此，获取值时，得到一个3x3的数组

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [9]:
# 花哨索引和简单索引组合
a[2, [2, 0, 1]]

array([10,  8,  9])

In [10]:
# 花哨索引与切片
a[:2, [2, 0, 1]]

array([[2, 0, 1],
       [6, 4, 5]])

In [11]:
# 花哨索引和掩码组合，下面的mask等价于np.array([True, False, True, False])
mask = np.array([1, 0, 1, 0], dtype=bool) # 这时只去下标为1对应的位置
row = np.array([0, 2])
a[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 8, 10]])

In [12]:
# 用花哨索引修改数组中部分元素的值
a = np.arange(10)
ind = np.array([2, 1, 5, 8])
a[ind] = 100
print(a)

[  0 100 100   3   4 100   6   7 100   9]


In [13]:
b = np.arange(12).reshape(3, 4)
row = np.array([0, 2])
col = np.array([1, 3])
b[row, col] = 100
b

array([[  0, 100,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 100]])