NumPy数组的合并

In [1]:
import numpy as np
a = np.arange(0, 6)
b = np.arange(6, 12)
a, b

(array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11]))

In [2]:
# concatenate()方法合并或连接两个一维数组
c = np.concatenate([a, b])
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# concatenate()方法合并或连接两个数组，具体指出沿着哪一个轴进行合并
# 本例是一维数组，只有axis=0这一个维度
d = np.concatenate([a, b], axis=0)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
# 利用a和b创建两个二维数组aa和bb
aa = a.reshape(2, -1)
bb = b.reshape(2, -1)
aa, bb

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]))

In [5]:
# 将aa和bb沿着axis=0（二维数组的行方向，或者理解为多维数组最大的维度，即该方向包含的元素数量最多）
# 要求在另一个维度（列）axis=1的方向上元素的个数必须是一样的
cc = np.concatenate([aa, bb], axis=0)
cc

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
# 将aa和bb沿着axis=1（二维数组的列方向，或者理解为多维数组的次大的维度）
# 要求沿着axis=0的方向上元素的个数必须是一样的
dd = np.concatenate([aa, bb], axis=1)
dd

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [7]:
# concatenate()方向也可以一次合并多个数组，只要其他维度符合规则即可
ee = np.concatenate([aa, bb, cc])
ee

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
x = np.array([[0, 1, 2]]) # 1x3
y = np.array([[1, 1, 1], [2, 2, 2]]) # 2x3
z = np.array([[3],[3]]) # 2x1

In [9]:
u = np.vstack([x, y]) #沿着垂直方向合并，要求垂直方向的元素个数相同，1x3与2x3满足
u # 效果跟沿着axis=0方向拼接相同

array([[0, 1, 2],
       [1, 1, 1],
       [2, 2, 2]])

In [10]:
uu = np.concatenate([x, y], axis=0)
uu

array([[0, 1, 2],
       [1, 1, 1],
       [2, 2, 2]])

In [11]:
v = np.hstack([y, z]) # 沿着水平方向合并，要求水平方向的元素个数相同，2x3与2x1满足
v # 效果跟沿着axis=1方向拼接相同

array([[1, 1, 1, 3],
       [2, 2, 2, 3]])

In [12]:
vv = np.concatenate([y, z], axis=1)
vv

array([[1, 1, 1, 3],
       [2, 2, 2, 3]])

In [13]:
# 除此之外，还有np.dstack()沿着第三个维度进行拼接数组
a = np.arange(30).reshape(2, 3, 5)
b = np.arange(29, -1, -1).reshape(2, 3, 5)
a, b

(array([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]],
 
        [[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]]),
 array([[[29, 28, 27, 26, 25],
         [24, 23, 22, 21, 20],
         [19, 18, 17, 16, 15]],
 
        [[14, 13, 12, 11, 10],
         [ 9,  8,  7,  6,  5],
         [ 4,  3,  2,  1,  0]]]))

In [14]:
c = np.dstack([a, b])
c

array([[[ 0,  1,  2,  3,  4, 29, 28, 27, 26, 25],
        [ 5,  6,  7,  8,  9, 24, 23, 22, 21, 20],
        [10, 11, 12, 13, 14, 19, 18, 17, 16, 15]],

       [[15, 16, 17, 18, 19, 14, 13, 12, 11, 10],
        [20, 21, 22, 23, 24,  9,  8,  7,  6,  5],
        [25, 26, 27, 28, 29,  4,  3,  2,  1,  0]]])

In [15]:
# 创建A, B, C三个矩阵
A = np.arange(0, 8).reshape(2, 4)
B = np.ones([2, 3])
C = np.zeros([3, 4])
A, B, C

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [16]:
# 拼接链接两个矩阵，要求两个矩阵A, B的行数相等
D = np.c_[A, B]
D

array([[0., 1., 2., 3., 1., 1., 1.],
       [4., 5., 6., 7., 1., 1., 1.]])

In [17]:
# 按行连接两个矩阵，要求两个矩阵A, C的列相等
E = np.r_[A, C]
E

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])