#### 数组分割

In [1]:
import numpy as np
a = np.arange(0, 15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [2]:
# 当split()函数的第二个参数为整数n时，将数组a切分为相等大小的n个子数组，要求a的元素个数能被第二个参数n整除
a1, a2, a3 = np.split(a, 3)
a1, a2, a3

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14]))

In [3]:
# 当split()函数的第二个参数为数组时（表示下标），该参数记录切分点位置，n个切分点会得到n+1个子数组
# 下面的hsplit()和vshplit()的用法类似
a1, a2, a3 = np.split(a, [2, 5])
a1, a2, a3

(array([0, 1]),
 array([2, 3, 4]),
 array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]))

In [4]:
b = np.reshape(a, [3, -1]) # b= a.reshape(3, -1) 结果一样
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
# 对于二维数组，split()方法还可以指定切分的方向，默认为axis=0
c = np.split(b, [2, 4], axis=1) #沿着列的方向切分
c

[array([[ 0,  1],
        [ 5,  6],
        [10, 11]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13]]),
 array([[ 4],
        [ 9],
        [14]])]

In [6]:
# 沿着水平方向切分，可以使用hsplit()，将数组切分为左右几个部分
d = np.hsplit(b, [2, 4])
d

[array([[ 0,  1],
        [ 5,  6],
        [10, 11]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13]]),
 array([[ 4],
        [ 9],
        [14]])]

In [7]:
# 沿着垂直水平方向切分，可以使用vshplit()，将数组切分为上下几个部分
e = np.vsplit(b, [2])
e

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]])]

In [8]:
# 多维数组，沿着第三维进行切分
f = np.arange(0, 24).reshape(1, 2, -1)
f

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]])

In [9]:
g = np.dsplit(f, [2, 5])
g

[array([[[ 0,  1],
         [12, 13]]]),
 array([[[ 2,  3,  4],
         [14, 15, 16]]]),
 array([[[ 5,  6,  7,  8,  9, 10, 11],
         [17, 18, 19, 20, 21, 22, 23]]])]