#### NumPy提供了大量的通用函数，既可以对标量和数组操作，也可以对两个数组进行操作

In [1]:
import numpy as np
a = np.arange(6).reshape(2, -1)
2 ** a

array([[ 1,  2,  4],
       [ 8, 16, 32]], dtype=int32)

In [2]:
# 取绝对值
b = np.arange(-5, 5)
b

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [3]:
c = np.abs(b) #也可以直接输入np.abs(b)得到输出
c

array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4])

In [4]:
# 取模
d = np.mod(b, 3)
d

array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1], dtype=int32)

In [5]:
# 更常用的取模操作，使用%
e = b % 3
e

array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1], dtype=int32)

In [6]:
# 三角函数，输出：角度，正弦，余弦，正切
theta = np.linspace(0, np.pi, 7)
theta, np.sin(theta), np.cos(theta), np.tan(theta)

(array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
        2.61799388, 3.14159265]),
 array([0.00000000e+00, 5.00000000e-01, 8.66025404e-01, 1.00000000e+00,
        8.66025404e-01, 5.00000000e-01, 1.22464680e-16]),
 array([ 1.00000000e+00,  8.66025404e-01,  5.00000000e-01,  6.12323400e-17,
        -5.00000000e-01, -8.66025404e-01, -1.00000000e+00]),
 array([ 0.00000000e+00,  5.77350269e-01,  1.73205081e+00,  1.63312394e+16,
        -1.73205081e+00, -5.77350269e-01, -1.22464680e-16]))

In [7]:
# 指数运算
x = np.arange(0, 5)
print(f"x = {x}, 2**x = {np.exp(x)} \ne^x = {np.exp(x)}, 4^x = {np.power(4, x)}")

x = [0 1 2 3 4], 2**x = [ 1.          2.71828183  7.3890561  20.08553692 54.59815003] 
e^x = [ 1.          2.71828183  7.3890561  20.08553692 54.59815003], 4^x = [  1   4  16  64 256]


In [8]:
# 对数运算
x = np.arange(1, 5)
print(f"ln(x) = {np.log(x)} \n log2(x) = {np.log2(x)} \n log10(x) = {np.log10(x)}")

ln(x) = [0.         0.69314718 1.09861229 1.38629436] 
 log2(x) = [0.        1.        1.5849625 2.       ] 
 log10(x) = [0.         0.30103    0.47712125 0.60205999]
