#### 数组比较、掩码和布尔逻辑

In [1]:
# 取出数组中比3小的元素
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5])
a < 3 # 这时可以得到a中比3小的元素对应的下标的值为True，比3大的元素对应的下标的值为False

array([ True,  True,  True, False, False, False])

In [2]:
a[a<3] # 取出比3小的元素，掩码的用法

array([0, 1, 2])

In [3]:
# 同理，可以获取>3的，!=3, >=3和==3等等的元素
a[a>3], a[a!=3], a[a>=3], a[a==3]

(array([4, 5]), array([0, 1, 2, 4, 5]), array([3, 4, 5]), array([3]))

In [4]:
# 统计a>3的元素个数
# 统计a>3的元素个数，也可以用np.sum()
print(np.count_nonzero(a > 3), np.sum(a>3)) # 这时判断a >3为True的值，被解释为1

2 2


In [5]:
# 判断a中是否存在>3的元素用any()，判断a中是否所有元素都>3的元素用all()
print(np.any(a > 3), np.all(a > 3))

True False


In [6]:
# 布尔运算，按位进行逻辑运算，按位与&，按位或|，按位异或^以及按位取反~
a = np.array([0, 1, 2, 3, 4, 5])
# 取出>1并且<4的元素，注意不能直接写成1 < a < 4，因为这是按位计算（各个元素进行判断）
a[(1 < a) & (a < 4)]

array([2, 3])

In [7]:
a[a > 3], a[~(a <= 3)] #等价

(array([4, 5]), array([4, 5]))

In [9]:
a = np.array([0, 2, 4, 6]) # 按位异或，例如6的二进制为110,3的二进制为011，异或得到101即5
b = np.array([0, 1, 2, 3])
a ^ b

array([0, 3, 6, 5], dtype=int32)