In [1]:
pwd

'E:\\workspace\\mlbook'

用np.array从Python列表创建数组

In [2]:
import numpy as np  #导入numpy

In [3]:
# 创建整数数组
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [4]:
# 创建多维数组
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Numpy要求数组的元素类型必须是相同的，如果不匹配，Numpy会自动向上转型（如果可行），
# 如果希望明确设置数组元素的类型，可使用dtype关键字指定
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
# 创建一个长度为5的全0数组
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
# 创建一个全1的2x4的浮点数组
np.ones([2, 4], dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# 创建一个3x4的浮点型数组，数组元素均为π的近似值
np.full([3, 4], np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [9]:
# 创建一个数组值是线性序列的数组，从0开始，20结束，步长为2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# 创建一个包含11个元素的数组，起取值在[0，1]之间等间隔分布
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [11]:
# 创建一个3x3的，服从0,1均匀分布的数组，
# 为了方便读者重现，这里设定随机种子，
# 读者只要使用相同的随机种子就可以得到相同的结果
np.random.seed(1)
np.random.random((3, 3))

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01]])

In [3]:
# 创建一个3x3的数组，其元素值服从0到10之间的均匀分布，
np.random.seed(1)
np.random.uniform(0, 10, [3, 3])

array([[4.17022005e+00, 7.20324493e+00, 1.14374817e-03],
       [3.02332573e+00, 1.46755891e+00, 9.23385948e-01],
       [1.86260211e+00, 3.45560727e+00, 3.96767474e+00]])

In [4]:
# 创建一个3x3的，均值为0，方差为1的正态分布随机数组
np.random.seed(1)
np.random.normal(0, 1, [3, 3])

array([[ 1.62434536, -0.61175641, -0.52817175],
       [-1.07296862,  0.86540763, -2.3015387 ],
       [ 1.74481176, -0.7612069 ,  0.3190391 ]])

In [13]:
# 创建一个3x3的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])