#### 数组的变形操作

In [1]:
import numpy as np
a = np.arange(0, 12) # 创建一个包含12个元素的一维数组
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
b = a.reshape(2, 6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [3]:
b[1, 1] = 100 # 修改b的元素b[1, 1]为100
# 查看数组a的数据，发现a[7]也变成100了，可见b只是a的视图，而不是独立的副本
a

array([  0,   1,   2,   3,   4,   5,   6, 100,   8,   9,  10,  11])

In [4]:
# 如果只要求将a表示为一个3行的二维数组，那么另外一个维度，可以由NumPy自动计算得到，只需输入-1
# 要求数组a的总长度可以被转换后得到的数组c的行数3整除，这时，得到一个3x4的数组
c = a.reshape(3, -1)
c

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [5]:
# 另一种常见的变形是将一个一维数组转变为二维数组
# 只需在所需增加的纬度上，添加关键字np.newaxis，这是该维度上元素的个数为1，该方法生成的新数组也是原书组的视图
a = np.arange(0, 6)
b = a[np.newaxis, :] # b是a在行（第0个维度）的位置上添加一个坐标，变成1x6的矩阵
b

array([[0, 1, 2, 3, 4, 5]])

In [6]:
# 将a转变为6行1列的数据，并将其第3行0列的元素修改为100
c = a[:, np.newaxis]
c[3, 0] = 100
c

array([[  0],
       [  1],
       [  2],
       [100],
       [  4],
       [  5]])

In [7]:
# 将二维数组转变为一维数组，可用flatten()方法
a = np.arange(0, 10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
b = a.flatten()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 如果二维数组中有一个维度为1，那么使用squeeze()方法也可以
a = np.arange(0, 10).reshape(-1, 1)
b = a.squeeze()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# 事实上，对于一维数组和多维数组的转换也是同样成立的
a = np.arange(0, 30).reshape(2, 3, 5)
a # a是一个3维的张量，这在图像处理中，彩色图像有3种颜色通道会使用得到

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [11]:
b = a.flatten() # 将3维张量转化为一维数组（向量）
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])