#### 数组的聚合操作

In [2]:
import numpy as np
np.random.seed(1)
a = np.random.randint(0, 50, 10) # 产生10个0到50之间的随机整数，构成一维数组
a

array([37, 43, 12,  8,  9, 11,  5, 15,  0, 16])

In [4]:
# 求a的最大值，最小值，平均值，以及对a的元素求和
print(f"max_a = {np.max(a)}, min_a = {np.min(a)}, mean_a = {np.mean(a)}, sum_a = {np.sum(a)}")

max_a = 43, min_a = 0, mean_a = 15.6, sum_a = 156


In [5]:
# 求a的标准差和方差
np.std(a), np.var(a)

(13.03993865016243, 170.04)

In [6]:
# 找出a中最大值和最小值的下标（索引）

In [7]:
np.argmax(a), np.argmin(a)

(1, 8)

In [8]:
# 计算数组a的中位数和分位数q，至少有百分之q的元素小于或等于计算得到的值
np.median(a), np.percentile(a, 25)

(11.5, 8.25)

In [9]:
# 求b中各个元素的积
b = np.array([1, 2, 3, 4])
np.prod(b)

24

In [10]:
# 对于多元数组，在进行聚合操作时，需要指定操作沿着哪一个轴axis
c = np.arange(12)
np.random.seed(1) #固定种子，方便读者重现，读者可修改种子进行测试
np.random.shuffle(c) # 就地打乱数组的顺序，没返回值，这个在机器学习样本的训练过程中，有时候会用到
c = np.reshape(c, [3, 4])

In [11]:
# 找出行的方向的最大值max，行最大值的下标argmax，机器学习的多元分类问题中，经常使用到
np.max(c, axis=0), np.argmax(c, axis=0)

(array([11,  9,  8, 10]), array([2, 2, 2, 0], dtype=int64))

In [12]:
# 找出列方向的最小值，列最小值的下标
np.min(c, axis=1), np.argmin(c, axis=1)

(array([2, 0, 5]), array([0, 2, 3], dtype=int64))

In [13]:
# 求出c沿着列的方向的和
np.sum(c, axis=1)

array([19, 14, 33])