#### 矩阵运算

In [1]:
# 创建矩阵，矩阵加法+，减法-
import numpy as np
a = np.arange(6).reshape(2, 3)
b = np.arange(5, -1, -1).reshape(2, 3)
print(f"a = \n {a} \n b = \n {b}")
print(f"a + b = \n {a + b}")
print(f"a - b = \n {a - b}")

a = 
 [[0 1 2]
 [3 4 5]] 
 b = 
 [[5 4 3]
 [2 1 0]]
a + b = 
 [[5 5 5]
 [5 5 5]]
a - b = 
 [[-5 -3 -1]
 [ 1  3  5]]


In [2]:
# 矩阵对应元素相乘
c = np.arange(6).reshape(2, 3)
d = np.arange(3)
print(f"(c = \n {c} \nd = \n {d}")

(c = 
 [[0 1 2]
 [3 4 5]] 
d = 
 [0 1 2]


In [3]:
c * d # 矩阵对应元素相乘，因为c和d的形状不同，这是需要用到前面小节的广播功能

array([[ 0,  1,  4],
       [ 0,  4, 10]])

In [4]:
# 矩阵相乘，有几种操作符或函数可以实现，np.dot(), np.matmul, 还有@（在Python 3.5 NumPy 1.10.0之后支持）
m1 = np.arange(6).reshape(2, 3)
m2 = np.arange(6).reshape(3, 2)
print(f"m1 = \n {m1}")
print(f"m2 = \n {m2}")
print(f"矩阵相乘方法1：m1.dot(m2) = \n {m1.dot(m2)}")
print(f"矩阵相乘方法2：np.dot(m1, m2) = \n {np.dot(m1, m2)}")
print(f"矩阵相乘方法3：np.matmul(m1, m2) = \n {np.matmul(m1, m2)}")
print(f"矩阵相乘方法4：m1 @ m2 = \n {m1 @ m2}")

m1 = 
 [[0 1 2]
 [3 4 5]]
m2 = 
 [[0 1]
 [2 3]
 [4 5]]
矩阵相乘方法1：m1.dot(m2) = 
 [[10 13]
 [28 40]]
矩阵相乘方法2：np.dot(m1, m2) = 
 [[10 13]
 [28 40]]
矩阵相乘方法3：np.matmul(m1, m2) = 
 [[10 13]
 [28 40]]
矩阵相乘方法4：m1 @ m2 = 
 [[10 13]
 [28 40]]


In [5]:
# 矩阵相乘究竟采用上述中哪一种方法，可根据自己喜好，注意不具有交换律
print(f"矩阵相乘m2 @ m1 = \n {m2 @ m1}")
print(f"矩阵相乘m1 @ m2 的结果和m2 @ m1 的结果，形状一般是不同的，(m1 @ m2).shape = {(m1 @ m2).shape}, (m2 @ m1).shape = {(m2 @ m1).shape}")

矩阵相乘m2 @ m1 = 
 [[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]
矩阵相乘m1 @ m2 的结果和m2 @ m1 的结果，形状一般是不同的，(m1 @ m2).shape = (2, 2), (m2 @ m1).shape = (3, 3)


In [6]:
# 矩阵的转置
print(f"m1 = \n {m1}")
print(f"(m1.T = \n {m1.T}")

m1 = 
 [[0 1 2]
 [3 4 5]]
(m1.T = 
 [[0 3]
 [1 4]
 [2 5]]


In [7]:
# 向量的内积，或向量与矩阵的点积，向量间的点积也可以运算
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([[1, 2], [3, 4]])
print(f"向量a和b的内积：{np.inner(a, b)}, 向量a和矩阵c的点积：{np.inner(a, c)}")

向量a和b的内积：11, 向量a和矩阵c的点积：[ 5 11]


In [9]:
# 矩阵的逆，需要用到线性代数包，若矩阵不可逆，则需要用到伪逆
a = np.array([[1, 2, 3], [2, 5, 7], [3, 8, 9]])
b = np.linalg.inv(a) # a的逆矩阵
c = a @ b # 单位阵
print(f"b = \n {b}")
print(f"c = \n {c}")

b = 
 [[ 5.5 -3.   0.5]
 [-1.5 -0.   0.5]
 [-0.5  1.  -0.5]]
c = 
 [[ 1.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [-2.77555756e-16  1.00000000e+00 -3.33066907e-16]
 [-1.05471187e-15  0.00000000e+00  1.00000000e+00]]


In [10]:
# 矩阵的迹，方正的主对角线元素的和1 + 5 + 9
np.trace(a)

15

In [11]:
# 矩阵的行列式
np.linalg.det(a)

-1.9999999999999998

In [12]:
# 矩阵特征值和特征向量
# w:多个特征值组成一个向量，多个特征值并没有按特定的次数排列，特征值可能包行复数，
# v:多个特征向量组成一个矩阵，每一个特征向量都被归一化了，第i列的特征向量v[:, i]对应第i个特征值w[i]
w, v = np.linalg.eig(a)
print(f"矩阵a的特征值w = {w}")
print(f"矩阵a的特征向量v = \n{v}")

矩阵a的特征值w = [15.63154682  0.16136309 -0.7929099 ]
矩阵a的特征向量v = 
[[-0.23914292 -0.96420521 -0.34645664]
 [-0.56494774  0.24210526 -0.67167816]
 [-0.78971179  0.10813585  0.65484062]]


In [13]:
# 矩阵的迹等于矩阵所有特征值的和，所以等于上面求出的15
np.sum(w)

15.000000000000009