#### 数组广播

In [1]:
import numpy as np
a = np.array([1, 2, 3]) # a是维数为1的向量，形状为(3,)
b = 3 # b是一个标量，没有形状属性
print(f"a.shape = {a.shape}, a + b = {a + b}") # 根据规则1，为了能与a进行计算，b扩展为维数1，形状(3,)的向量

a.shape = (3,), a + b = [4 5 6]


In [2]:
# 相当于 a = np.array([1, 2, 3]) 和 b = np.array([3, 3, 3])两个数据的和
a = np.array([1, 2, 3])
b = np.array([3, 3, 3])
print(f"a.shape = {a.shape}, a + b = {a + b}")

a.shape = (3,), a + b = [4 5 6]


In [3]:
a = np.arange(6).reshape(2, 3) # a是一个维数为2，形状为(2,3)的数组（矩阵）
b = 3
print(f"a.shape = {a.shape} \n a + b = \n {a + b}") # 根据规则1，为了能与a进行计算，b扩展为维数2，形状(2,3)的矩阵

a.shape = (2, 3) 
 a + b = 
 [[3 4 5]
 [6 7 8]]


In [4]:
# 等价于下面的操作
a = np.arange(6).reshape(2, 3) # a是一个维数为2，形状为(2,3)的数组（矩阵）
b = np.array([[3, 3, 3,], [3, 3, 3]]) # b是一个维数为2，形状为(2, 3)的数组
print(f"a.shape = {a.shape} \n a + b = \n {a + b}") # 根据规则1，为了能与a进行计算，b扩展为维数2，形状(2,3)的矩阵

a.shape = (2, 3) 
 a + b = 
 [[3 4 5]
 [6 7 8]]


In [5]:
a = np.arange(6).reshape(2, 3) # a是一个维数为2，形状为（2,3）的数组（矩阵）
b= np.arange(3) # b是一个维数为1，形状为(3,)的向量
# 根据规则1，a和b的维数不同，形状先右对齐，然后b的形状左边补1，则得到(1,3),这时，两个数据的维数相同
# 但a和b的形状不匹配，根据规则2，不匹配的维度上有一个是1，可将其扩张为另一个数组的形状，这样b的形状变为(2,3)
# 就可以进行计算了，这就是广播
a + b

array([[0, 2, 4],
       [3, 5, 7]])

In [6]:
# 等价于
a = np.arange(6).reshape(2, 3) # a是一个维数为2，形状为（2,3）的数组（矩阵）
b= np.array([[0, 1, 2,], [0, 1, 2]]) # b是一个维数为3，形状为(2, 3)的向量
a + b

array([[0, 2, 4],
       [3, 5, 7]])

In [7]:
# 准备测试数据，a是一个维数为3（可用a.ndim查看维数），形状为(2,3,1)的数组（张量）
a = np.arange(6).reshape(2, 3, 1)
b = np.arange(3) # b是一个维数为1，形状为(3,)的数组
print(f"(a = {a}, b = {b}")

(a = [[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]], b = [0 1 2]


In [8]:
# a和b的形状分别是(2, 3, 1)和(3,),维数不一致，根据规则1，首先形状右对齐，然后维数小的形状在左边补1
# 得到b'的形状为(1, 1, 3)，这是a和b的维数都是3根据规则2，对应维度不匹配的形状中，都有一个是1
# 将之扩展到另一个数组的形状，所以a的第3个维度张展至3，b的第1，第2个维度分别扩展值2和3，最终两个数组都是(2, 3, 3)的形状
c = a + b
print(f"c = {c}, c.shape = {c.shape}")

c = [[[0 1 2]
  [1 2 3]
  [2 3 4]]

 [[3 4 5]
  [4 5 6]
  [5 6 7]]], c.shape = (2, 3, 3)


In [9]:
# a的形状是(2, 3)，b的形状是(2,)，由规则1，先将b扩展至(1, 2)
# 但这是a和b的最右边的形状不匹配，且没有一个是1，根据规则2，无法广播，从而产生异常
a = np.arange(6).reshape(2, 3)
b = np.arange(2)
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 