数组索引，Numpy数组的单个元素引用跟Python列表的单个元素引用一样

In [1]:
# 一维数组的元素引用
import numpy as np
a = np.array([0, 1, 2, 3, 4])
a[1]

1

In [2]:
# 二维数组的元素引用，可以用a[i][j],也可以用a[i, j]
b = np.array([[0, 1, 2], [3, 4, 5]])
b[0][1]

1

In [3]:
b[1, 2]

5

In [4]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 取出a的前5个元素
a[:5]

array([0, 1, 2, 3, 4])

In [6]:
# 取出a的2至4个元素
a[2:5]

array([2, 3, 4])

In [7]:
# 取出a的下标为奇数的元素
a[1::2]

array([1, 3, 5, 7, 9])

In [8]:
# 有时候想要逆序取出数组最后几个元素，可以采用步长为负数的方式，例如逆序每个一个元素取出a中的3个元素
a[:-6:-2]

array([9, 7, 5])

In [9]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
# 取出数组a的前2行，前3列
a[:2, :3]

array([[0, 1, 2],
       [4, 5, 6]])

In [11]:
# 特别注意，这个时候使用a[:2][:3]会得到不一样的结果
a[:2][:3]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

a[:2][:3]的计算逻辑是先得到a的前2行a[:2]，在这结果的基础上，
再去得到它的前3"列"（实际上是得到中间结果的前3行）

In [12]:
b = a[:2] # b是a的前2行数据
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [13]:
b[:3] # 取出b的前3行数据，但因为b是一个2x4的数组，并没有3行，所以只能取出前2行

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

获取数组的行和列

In [14]:
# 一种很常见的需求是获取数组的但行和单列
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
a1 = a[:, 1]
a1

array([1, 5, 9])

In [16]:
# 在获取行时，NumPy提供了简洁的语法表达，既可以用a[1,:]也可以用a[1]得到第一行的数据
a[1,:]

array([4, 5, 6, 7])

In [17]:
a[1]

array([4, 5, 6, 7])

In [18]:
a = np.array(np.arange(12).reshape(3,4)) # reshape方法后面会讲到
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
sub_a = a[:2, :2] # sub_a为a的前两行两列
sub_a

array([[0, 1],
       [4, 5]])

In [20]:
sub_a[1, 1] = 100 # 修改sub_a第1行1列的元素值为100

In [21]:
a # 查看a的值，发现a[1, 1]的值也跟着变成100了

array([[  0,   1,   2,   3],
       [  4, 100,   6,   7],
       [  8,   9,  10,  11]])

In [22]:
a = np.array(np.arange(12).reshape(3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
sub_a_copy = a.copy() # sub_a_copy是a的一个副本
sub_a_copy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
sub_a_copy[1, 1] = 100 # 修改sub_a_copy的第1行1列的元素为100，并查看修改是否成功
sub_a_copy

array([[  0,   1,   2,   3],
       [  4, 100,   6,   7],
       [  8,   9,  10,  11]])

In [25]:
a # 查看a是否跟着变化，可以发现，a仍然保留原来的数据，跟sub_a_copy是独立的两份数据

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])